# Generated by Django 5.2.1 on 2025-06-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Curso')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('imagen_1', models.ImageField(upload_to='cursos', verbose_name='Imagen 1')),
                ('imagen_2', models.ImageField(upload_to='cursos', verbose_name='Imagen 2')),
                ('imagen_3', models.ImageField(upload_to='cursos', verbose_name='Imagen 3')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created'],
            },
        ),
    ]
