# Generated by Django 5.2.1 on 2025-06-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['-created'], 'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructores'},
        ),
    ]
